In [8]:
##below code is just to see hoe the tes works
import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
response = stats.ks_2samp(sample1, sample2)  ##this function will check whether these sample1 and smaple2 belongs to the same distribution, on the basis of it , it will calculate some values tha we have stored in the response

In [9]:
sample1

array([0.03684494, 0.02886998, 0.27762738, 0.54322935, 0.26262791,
       0.51535366, 0.40731816, 0.10110008, 0.46836107, 0.50606765,
       0.13271812, 0.78449164, 0.67633873, 0.60442477, 0.96954529,
       0.00833088, 0.80275632, 0.14957918, 0.90699195, 0.58109457,
       0.1461572 , 0.38793831, 0.32178756, 0.58882434, 0.3322744 ,
       0.17261028, 0.66653028, 0.14001321, 0.0837424 , 0.91853567,
       0.96703471, 0.24466067, 0.81251257, 0.30864074, 0.35453433,
       0.5564621 , 0.84857116, 0.65237709, 0.17688567, 0.70984505,
       0.84935377, 0.74081894, 0.86480221, 0.04143969, 0.95402553,
       0.88087706, 0.56864197, 0.8071988 , 0.94911426, 0.37796382,
       0.18821248, 0.56794676, 0.76996717, 0.4949389 , 0.40237791,
       0.12422799, 0.20804094, 0.93560474, 0.041185  , 0.83232489,
       0.80010946, 0.98183425, 0.5867536 , 0.02710404, 0.79028998,
       0.46730518, 0.99892232, 0.98459317, 0.24711359, 0.26832501,
       0.58129081, 0.10485093, 0.7252635 , 0.77759547, 0.23992

In [10]:
sample2

array([-1.12113581, -1.38645329,  0.30503707, -0.0503653 ,  0.79267112,
       -0.112952  ,  0.1151852 , -0.10754926, -0.73009928, -0.09765319,
       -0.3145506 ,  1.28831434,  1.03945217, -0.11818795, -1.0937352 ,
        1.2657191 , -0.38143287,  0.29909718,  2.99865457,  0.27021221,
       -0.60997804, -1.00987065,  1.23872328,  0.46633985,  0.66715932,
       -0.66173549, -0.02323625, -0.63880681, -0.30617099,  0.21633754,
        1.40543011, -1.89988988, -0.46985153,  0.67263206, -0.19023592,
       -0.79606781,  1.36906275,  1.53187604, -1.22375658,  0.29040849,
        1.05048257,  1.58700202, -0.36025769, -0.91367148,  0.80187565,
        1.13475326,  0.29665008, -0.21934553, -0.79680029, -0.2635632 ,
        1.51044772, -1.20187653, -2.4293328 ,  0.35740496, -0.53104634,
       -1.44057201, -1.25605891, -0.73937787,  0.98557069, -1.6109654 ,
        0.33831303, -0.3552138 , -0.05322548, -1.07150625, -1.3014785 ,
       -0.85218239,  0.99055725,  0.22911315, -2.36485154,  0.98

In [11]:
response.pvalue   ##if my pvalue is less than 0.05, then we will reject null hypothesis{i.e., the distribution is different}

1.570083959660037e-17

In [15]:
#round(response.pvalue)

In [16]:
#round(response.pvalue,16)  ##even if we round it up upto16 decimals then also it is showing 0

In [14]:
round(response.pvalue,17) ##so basically it is very small, and ofcourse smaller than 0.05, therefore we reject the null hypothesis, i.e., these both samples are not from same distribution,,and it is very obvious as we have taken sample1 as uniform distribution and sample2 as normal distribution{this we have done just to understand how this function works}

2e-17

**When we get pvalue like this, we say that the distribution of our data is changed, i.e., there is data drift, now we will have to do the retraining, i.e., the whole EDA,FE , then experiment with the models to get the most effective one need to be done.**

Now i will have to do the **Anomly detection** in my dataset, the possible anamolies that can be there:
1. High no. of Null Values
2. Missing COlumns
3. Outlier
4. Categorical columns: 
   eg. suppose in base dataset's Gender column categories present are--> MALE, FEMALE but when we get the new data there are three categories in thi sparticular column--> MALE, FEMALE, Others. So we have to check this kind of mismatch in categorical columns.
5. If there any imbalance introdced in the new dataset{resolve it by using oversampling, undersampling etc methods} 
6. Target drift{target column distribution change, like in case o categorical type target column, there is change in the number of categories like the one we saw in the 4th point, this target drift could be checked individually by using the function and in it instead of samples use targets}
7. concept drift, i.e., change in the  relation of target feature with other input features{this could be checked by using the correlation values}

*

*

*

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/config/workspace/artifact/12302022__093948/data_ingestion/dataset/train.csv")

In [4]:
df.head()

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0   neg      22     2.0    44.0     NaN     0.0     0.0     0.0     0.0   
1   neg      10     NaN     0.0     0.0     0.0     0.0     0.0     0.0   
2   neg   41474     NaN   598.0     NaN     0.0     0.0     0.0     0.0   
3   neg   18928     NaN  1406.0  1406.0     0.0     0.0     0.0     0.0   
4   neg      26     NaN    20.0    20.0     0.0     0.0     0.0     0.0   

   ag_002  ...    ee_002    ee_003    ee_004    ee_005    ee_006    ee_007  \
0  3454.0  ...     196.0      34.0      46.0      24.0      10.0       0.0   
1     0.0  ...      36.0      26.0      36.0      46.0     100.0      26.0   
2     0.0  ...  331610.0  177770.0  348412.0  315844.0  237834.0  148534.0   
3     0.0  ...   58134.0    5134.0    1764.0      92.0      14.0       0.0   
4     0.0  ...     508.0      76.0      72.0       0.0       0.0       0.0   

     ee_008   ee_009  ef_000  eg_000  
0       0.0      0.0     0.0     0.0  
1       0.0      0.0     0.0     0.0  
2  258180.0  15748.0     0.0     0.0  
3       0.0      0.0     0.0     0.0  
4       0.0      0.0     0.0     0.0  

[5 rows x 171 columns]

In [5]:
df.isnull().sum()

class         0
aa_000        0
ab_000    22358
ac_000     1723
ad_000     7413
          ...  
ee_007      305
ee_008      305
ee_009      305
ef_000     1398
eg_000     1397
Length: 171, dtype: int64

In [6]:
df.isnull().sum()/df.shape[0]  ##this will give the percentage of the null values in each column

class     0.000000
aa_000    0.000000
ab_000    0.772297
ac_000    0.059516
ad_000    0.256062
            ...   
ee_007    0.010535
ee_008    0.010535
ee_009    0.010535
ef_000    0.048290
eg_000    0.048256
Length: 171, dtype: float64

In [8]:
(df.isnull().sum()/df.shape[0]).values  ##this will have percentage of all columns in an array form

array([0.        , 0.        , 0.77229706, 0.05951641, 0.25606218,
       0.04431779, 0.04431779, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01098446, 0.01074266, 0.01074266,
       0.0784456 , 0.01088083, 0.01074266, 0.01088083, 0.00974093,
       0.01088083, 0.00974093, 0.04825561, 0.01074266, 0.01074266,
       0.01074266, 0.04435233, 0.04435233, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01098446, 0.04829016,
       0.04829016, 0.04438687, 0.04431779, 0.01088083, 0.01088083,
       0.00974093, 0.00974093, 0.37920553, 0.44770294, 0.65274

In [9]:
(df.isnull().sum()/df.shape[0]).index ##using this can fetch the column names

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [12]:
for column_name, missing_percentage in zip((df.isnull().sum()/df.shape[0]).index, (df.isnull().sum()/df.shape[0]).values):
    print(column_name, missing_percentage*100)

class 0.0
aa_000 0.0
ab_000 77.22970639032816
ac_000 5.951640759930915
ad_000 25.606217616580313
ae_000 4.431778929188256
af_000 4.431778929188256
ag_000 1.0535405872193437
ag_001 1.0535405872193437
ag_002 1.0535405872193437
ag_003 1.0535405872193437
ag_004 1.0535405872193437
ag_005 1.0535405872193437
ag_006 1.0535405872193437
ag_007 1.0535405872193437
ag_008 1.0535405872193437
ag_009 1.0535405872193437
ah_000 1.0984455958549224
ai_000 1.07426597582038
aj_000 1.07426597582038
ak_000 7.844559585492227
al_000 1.0880829015544042
am_0 1.07426597582038
an_000 1.0880829015544042
ao_000 0.9740932642487047
ap_000 1.0880829015544042
aq_000 0.9740932642487047
ar_000 4.825561312607944
as_000 1.07426597582038
at_000 1.07426597582038
au_000 1.07426597582038
av_000 4.435233160621762
ax_000 4.435233160621762
ay_000 1.0535405872193437
ay_001 1.0535405872193437
ay_002 1.0535405872193437
ay_003 1.0535405872193437
ay_004 1.0535405872193437
ay_005 1.0535405872193437
ay_006 1.0535405872193437
ay_007 1.0535

In [13]:
drop_column_names=[]
for column_name, missing_percentage in zip((df.isnull().sum()/df.shape[0]).index, (df.isnull().sum()/df.shape[0]).values):
    print(column_name, missing_percentage*100)
    if missing_percentage>0.3:
        drop_column_names.append(column_name)

class 0.0
aa_000 0.0
ab_000 77.22970639032816
ac_000 5.951640759930915
ad_000 25.606217616580313
ae_000 4.431778929188256
af_000 4.431778929188256
ag_000 1.0535405872193437
ag_001 1.0535405872193437
ag_002 1.0535405872193437
ag_003 1.0535405872193437
ag_004 1.0535405872193437
ag_005 1.0535405872193437
ag_006 1.0535405872193437
ag_007 1.0535405872193437
ag_008 1.0535405872193437
ag_009 1.0535405872193437
ah_000 1.0984455958549224
ai_000 1.07426597582038
aj_000 1.07426597582038
ak_000 7.844559585492227
al_000 1.0880829015544042
am_0 1.07426597582038
an_000 1.0880829015544042
ao_000 0.9740932642487047
ap_000 1.0880829015544042
aq_000 0.9740932642487047
ar_000 4.825561312607944
as_000 1.07426597582038
at_000 1.07426597582038
au_000 1.07426597582038
av_000 4.435233160621762
ax_000 4.435233160621762
ay_000 1.0535405872193437
ay_001 1.0535405872193437
ay_002 1.0535405872193437
ay_003 1.0535405872193437
ay_004 1.0535405872193437
ay_005 1.0535405872193437
ay_006 1.0535405872193437
ay_007 1.0535

In [14]:
drop_column_names  ##all the columns that are to be dropped as have missing values more than 30 percentage

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [17]:
##or, thia way also we can get which columns have null percentage greater than 30 percentage, it is basically a short code w.r.t the first one
null_report = df.isna().sum()/df.shape[0]
null_report[null_report>0.3].index

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')

In [18]:
len(df.iloc[:,[0]].drop("class",axis=1).columns)  ##located the first column with all the row values, which was "class", then dropeed it then counted the number of column in this located dataframe, obviously it will return zero, kyuki jisko locate kia usiko drop kar dia to ab kya hi bachega

0

In [ ]:
from glob import glob

In [ ]:
glob("/config/workspace/saved_models/1/**/*.pkl")

['/config/workspace/saved_models/1/model/model.pkl']

In [ ]:
import os

os.path.basename("saved_mode/1")

'1'